using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//tinfo200:[2021-03-11-kylelam-dykstra1] - So we are able to use the datqabase generated feature
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    //tinfo200:[2021-03-11-kylelam-dykstra1] - creating the course entity, all the features of a course. 
    public class Course
    {
        //tinfo200:[2021-03-11-kylelam-dykstra1] - This will affect the courseId, it will make the course id not be generated by the database instead can be entered by the pk.  
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }
    }
}
